[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
radsort = "0.1.1"
rustc-hash = "2.1.0"


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "aoc"
harness = false
path = "src/bench.rs"



[profile.release]
debug = true
